version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    networks:
      - backend_network

  redis:
    image: redis:6.2.6
    command: ['redis-server', '--notify-keyspace-events', 'Ex']
    container_name: redis_container
    ports:
      - '6380:6379'
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mongodb_data:
